# Generated by Django 4.2.7 on 2025-07-01 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('metric_type', models.CharField(choices=[('counter', 'Counter'), ('gauge', 'Gauge'), ('histogram', 'Histogram'), ('summary', 'Summary')], max_length=15)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tags', models.JSONField(default=dict, help_text='Metric tags/labels')),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Metric',
                'verbose_name_plural': 'Analytics Metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('dashboard_type', models.CharField(choices=[('overview', 'Overview Dashboard'), ('financial', 'Financial Dashboard'), ('operations', 'Operations Dashboard'), ('analytics', 'Analytics Dashboard'), ('custom', 'Custom Dashboard')], max_length=15)),
                ('layout_config', models.JSONField(default=dict, help_text='Dashboard layout configuration')),
                ('widgets_config', models.JSONField(default=list, help_text='Dashboard widgets configuration')),
                ('allowed_roles', models.JSONField(default=list, help_text='List of roles that can access this dashboard')),
                ('is_default', models.BooleanField(default=False, help_text='Default dashboard for new users')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('widget_type', models.CharField(choices=[('chart', 'Chart Widget'), ('metric', 'Metric Widget'), ('table', 'Table Widget'), ('list', 'List Widget'), ('calendar', 'Calendar Widget'), ('progress', 'Progress Widget'), ('custom', 'Custom Widget')], max_length=15)),
                ('chart_type', models.CharField(blank=True, choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('doughnut', 'Doughnut Chart'), ('area', 'Area Chart'), ('scatter', 'Scatter Plot')], max_length=15, null=True)),
                ('data_source', models.CharField(help_text='Source of data for the widget', max_length=200)),
                ('query_config', models.JSONField(default=dict, help_text='Query configuration for data retrieval')),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=4)),
                ('height', models.PositiveIntegerField(default=3)),
                ('display_config', models.JSONField(default=dict, help_text='Widget display configuration')),
                ('refresh_interval', models.PositiveIntegerField(default=300, help_text='Refresh interval in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('filters_applied', models.JSONField(default=dict, help_text='Filters applied when generating the report')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('download', 'Downloaded'), ('email', 'Emailed'), ('share', 'Shared')], max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report Access',
                'verbose_name_plural': 'Report Accesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class name', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report Category',
                'verbose_name_plural': 'Report Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('report_type', models.CharField(choices=[('financial', 'Financial Report'), ('loans', 'Loans Report'), ('equipment', 'Equipment Report'), ('membership', 'Membership Report'), ('contributions', 'Contributions Report'), ('custom', 'Custom Report')], max_length=15)),
                ('sql_query', models.TextField(blank=True, help_text='SQL query for custom reports', null=True)),
                ('fields_config', models.JSONField(default=dict, help_text='Configuration for report fields')),
                ('filters_config', models.JSONField(default=dict, help_text='Available filters for the report')),
                ('allowed_roles', models.JSONField(default=list, help_text='List of roles that can access this report')),
                ('is_public', models.BooleanField(default=False)),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('generation_time', models.TimeField(default='09:00:00')),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('email_recipients', models.TextField(blank=True, help_text='Additional email addresses (comma-separated)', null=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('inactive', 'Inactive')], default='active', max_length=15)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'ordering': ['name'],
            },
        ),
    ]
