# Generated by Django 4.2.7 on 2025-07-01 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scheduled_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='recipients',
            field=models.ManyToManyField(related_name='scheduled_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='reports.reporttemplate'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='reports.reportcategory'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportaccess',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='reports.generatedreport'),
        ),
        migrations.AddField(
            model_name='reportaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='reports.reporttemplate'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.dashboard'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['name', 'date'], name='reports_ana_name_f6b2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['metric_type', 'timestamp'], name='reports_ana_metric__4b4e80_idx'),
        ),
        migrations.AddIndex(
            model_name='reportaccess',
            index=models.Index(fields=['report', 'action'], name='reports_rep_report__0fe13b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportaccess',
            index=models.Index(fields=['user', 'created_at'], name='reports_rep_user_id_686cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['requested_by', 'status'], name='reports_gen_request_aa3deb_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['template', 'status'], name='reports_gen_templat_272848_idx'),
        ),
    ]
